[tool.poetry]
name = "discordllm"
version = "0.1.0"
description = ""
authors = ["Mikeymoo5 <moodids@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
py-cord = "^2.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
